
import diceImg from "../assets/image/dice.png";
import diceGroupImg from "../assets/image/diceGroup.png";
import signlogoImg from "../assets/image/signlogo.png";
import pedImg from "../assets/image/ped.png";
import diceGroup1Img from "../assets/image/diceGroup1.svg";
import gameImg from "../assets/image/game.svg";
import daoImg from "../assets/image/dao.png";
import chartImg from "../assets/image/chart.svg";
import traderjoeImg from "../assets/image/traderjoe.svg";
import plusImg from "../assets/image/plus.png";
import minusImg from "../assets/image/minus.png";
import nft1Img from "../assets/image/nft1.png";
import discordImg from "../assets/image/discord.png";
import telegramImg from "../assets/image/telegram.png";
import youtubeImg from "../assets/image/youtube.png";
import mediumImg from "../assets/image/medium.png";
import avaxImg from "../assets/image/avax.png";

export const dice = diceImg;
export const diceGroup = diceGroupImg;
export const signlogo = signlogoImg;
export const ped = pedImg;
export const diceGroup1 = diceGroup1Img;
export const game = gameImg;
export const dao = daoImg;
export const chart = chartImg;
export const traderjoe = traderjoeImg;
export const plus = plusImg;
export const minus = minusImg;
export const nft1 = nft1Img;
export const discord = discordImg;
export const telegram = telegramImg;
export const youtube = youtubeImg;
export const medium = mediumImg;
export const avax = avaxImg;