
import diceImg from "../assets/image/dice.png";
import diceGroupImg from "../assets/image/diceGroup.png";
import signlogoImg from "../assets/image/signlogo.png";
import pedImg from "../assets/image/ped.png";
import diceGroup1Img from "../assets/image/diceGroup1.svg";
import gameImg from "../assets/image/game.svg";
import daoImg from "../assets/image/dao.png";
import chartImg from "../assets/image/chart.svg";
import traderjoeImg from "../assets/image/traderjoe.svg";
import plusImg from "../assets/image/plus.png";
import minusImg from "../assets/image/minus.png";
import nft1Img from "../assets/image/nft1.png";
import discordImg from "../assets/image/discord.png";
import telegramImg from "../assets/image/telegram.png";
import youtubeImg from "../assets/image/youtube.png";
import mediumImg from "../assets/image/medium.png";
import avaxImg from "../assets/image/avax.png";
import rarediceImg from "../assets/image/raredice.png";
import avatar2Img from "../assets/image/avatar2.webp";
import avatar211Img from "../assets/image/avatar211.webp";
import avatar559Img from "../assets/image/avatar559.webp";
import avatar844Img from "../assets/image/avatar844.webp";
import avatar956Img from "../assets/image/avatar956.webp";
import avatar987Img from "../assets/image/avatar987.webp";
import progressSignImg from "../assets/image/progressSign.png";
import snowyImg from "../assets/image/snowy.png";
import pureImg from "../assets/image/pure.png";
import samImg from "../assets/image/sam.png";
import user101Img from "../assets/image/user101.png";
import mikeImg from "../assets/image/mike.png";

export const dice = diceImg;
export const diceGroup = diceGroupImg;
export const signlogo = signlogoImg;
export const ped = pedImg;
export const diceGroup1 = diceGroup1Img;
export const game = gameImg;
export const dao = daoImg;
export const chart = chartImg;
export const traderjoe = traderjoeImg;
export const plus = plusImg;
export const minus = minusImg;
export const nft1 = nft1Img;
export const discord = discordImg;
export const telegram = telegramImg;
export const youtube = youtubeImg;
export const medium = mediumImg;
export const avax = avaxImg;
export const raredice = rarediceImg;
export const avatar2 = avatar2Img;
export const avatar211 = avatar211Img;
export const avatar559 = avatar559Img;
export const avatar844 = avatar844Img;
export const avatar956 = avatar956Img;
export const avatar987 = avatar987Img;
export const progressSign = progressSignImg;
export const snowy = snowyImg;
export const pure = pureImg;
export const sam = samImg;
export const user101 = user101Img;
export const mike = mikeImg;