export { default as NotFound } from "./404";
export { default as Dashboard } from "./Dashboard";
export { default as Gameplay } from "./Gameplay";
export { default as Dao } from "./Dao";
export { default as Beta } from "./Beta";
export { default as Token } from "./Token";
export { default as Minting } from "./Minting";
export { default as Staking } from "./Staking";
export { default as Publicsale } from "./Publicsale";
